spring: 
	profiles: 
		active: 
		- dev
---
server: 
	port: 8001
spring: 
   application: 
     name: ioutSourcing-core
   datasource: 
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: oracle.jdbc.driver.OracleDriver 
     url: jdbc:oracle:thin:@localhost:1521:orcl 
     username: C##tom 
     password: tom
   dbcp2: 
      min-idle: 5
      inital-size: 5
      max-total: 5
      max-wait-millis: 200
eureka: 
   client: 
      service-url: 
         defaultZone: http://eureka01.com:7001/eureka
   instance: 
      instance-id: Jerry-core
      perfer-ip-address: true
      
info: 
   app.name: IoutSourcing_core
   company.name: www.huawei.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$